from controladores.controlador_sistema import ControladorSistema
from controladores.controlador_bebida import ControladorBebida
from controladores.controlador_conta import ControladorConta
from controladores.controlador_produto import ControladorProduto
from controladores.controlador_prato import ControladorPrato